FROM alpine:3.4
MAINTAINER BJ Choi bjchoi.3698@gmail.com
# Run a few package install for test purpose
RUN apk update
RUN apk add vim
RUN apk add curl
  
# Later replace vim with git in the 2nd build
# RUN apk add git
